# Generated by Django 4.2.5 on 2024-02-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0006_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
