# Generated by Django 4.2.5 on 2024-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
    ]
