# Generated by Django 4.2.5 on 2024-02-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enapp', '0004_category_type_product_created_at_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='mediafiles/event/images')),
                ('date', models.DateField()),
                ('voice', models.FileField(blank=True, upload_to='mediafiles/event/voices')),
                ('attachment', models.FileField(blank=True, upload_to='mediafiles/event/attachments')),
            ],
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
